#!/usr/bin/env python3
# modules/evade_detect.py — WAF/CDN/Firewall detection for CLVX

import re
from modules.base import BaseModule
from utils.colors import Colors, print_status, print_section
from utils.http_client import CLVXHTTPClient

FINGERPRINTS = [
    ("Cloudflare",      "CDN/WAF",   "header_key", ["cf-ray", "cf-cache-status", "cf-request-id"]),
    ("Cloudflare",      "CDN/WAF",   "header_val", ["cloudflare"]),
    ("Cloudflare",      "CDN/WAF",   "cookie",     ["__cfduid", "__cfuid", "cf_clearance"]),
    ("Cloudflare",      "CDN/WAF",   "body",       ["attention required! | cloudflare", "ray id"]),
    ("AWS WAF",         "WAF",       "header_val", ["awselb", "x-amzn-requestid", "x-amzn-trace-id"]),
    ("AWS CloudFront",  "CDN",       "header_key", ["x-amz-cf-id", "x-amz-cf-pop"]),
    ("AWS CloudFront",  "CDN",       "header_val", ["cloudfront"]),
    ("AWS ALB",         "LB",        "header_val", ["awselb", "awsalb"]),
    ("Akamai",          "CDN/WAF",   "header_key", ["akamai-grn", "x-akamai-transformed"]),
    ("Akamai",          "CDN/WAF",   "header_val", ["akamai"]),
    ("Akamai",          "CDN/WAF",   "body",       ["access denied | akamai"]),
    ("Fastly",          "CDN",       "header_key", ["x-fastly-request-id", "x-served-by"]),
    ("Fastly",          "CDN",       "header_val", ["fastly"]),
    ("Sucuri",          "WAF",       "header_key", ["x-sucuri-id", "x-sucuri-cache"]),
    ("Sucuri",          "WAF",       "body",       ["sucuri webiste firewall", "access denied - sucuri"]),
    ("Imperva",         "WAF",       "header_key", ["x-iinfo", "x-cdn"]),
    ("Imperva",         "WAF",       "cookie",     ["visid_incap", "incap_ses"]),
    ("Imperva",         "WAF",       "body",       ["incapsula incident", "_incap_"]),
    ("F5 BIG-IP",       "WAF/LB",    "header_val", ["bigip", "f5"]),
    ("F5 BIG-IP",       "WAF/LB",    "cookie",     ["bigipserver", "f5_cspm"]),
    ("Barracuda",       "WAF",       "body",       ["barracuda networks", "barra_counter_session"]),
    ("Barracuda",       "WAF",       "cookie",     ["barra_counter_session"]),
    ("ModSecurity",     "WAF",       "header_val", ["mod_security", "modsecurity"]),
    ("ModSecurity",     "WAF",       "body",       ["mod_security", "this error was generated by mod_security"]),
    ("Nginx",           "Server",    "header_val", ["nginx"]),
    ("Varnish",         "Cache",     "header_key", ["x-varnish", "via"]),
    ("Varnish",         "Cache",     "header_val", ["varnish"]),
    ("Azure Front Door","CDN/WAF",   "header_key", ["x-azure-ref", "x-fd-healthprobe"]),
    ("Azure CDN",       "CDN",       "header_val", ["microsoft", "azure"]),
    ("Google Cloud",    "CDN/LB",    "header_key", ["x-cloud-trace-context", "x-goog-iap-generated-response"]),
    ("GCP Load Bal.",   "LB",        "header_val", ["gws", "google frontend"]),
]

WAF_TEST_PAYLOADS = [
    ("SQLi probe",       "?id=1'%20OR%20'1'='1"),
    ("XSS probe",        "?q=<script>alert(1)</script>"),
    ("Path traversal",   "?file=../../../etc/passwd"),
    ("Command inj.",     "?cmd=;id"),
    ("Scanner UA",       None),
]

SCANNER_UAS = [
    "sqlmap/1.7.8",
    "Nikto/2.1.6",
    "Nmap Scripting Engine",
    "DirBuster-1.0-RC1",
]


class WAFDetector(BaseModule):

    NAME        = "evade/detect"
    DESCRIPTION = "Detect WAF, CDN, and firewall — fingerprints 20+ providers, tests response to attack payloads"
    REFERENCES  = [
        "https://github.com/EnableSecurity/wafw00f",
        "https://owasp.org/www-community/attacks/",
    ]

    def _define_options(self):
        self._add_option("TARGET",   "",     True,  "Target URL (e.g. https://target.com)")
        self._add_option("TIMEOUT",  "10",   False, "Request timeout in seconds")
        self._add_option("PAYLOADS", "true", False, "Send WAF test payloads (true/false)")
        self._add_option("DELAY",    "0.5",  False, "Delay between requests in seconds")

    def run(self) -> list:
        if not self._validate():
            return []

        target   = self.get_option("TARGET").strip().rstrip("/")
        timeout  = int(self.get_option("TIMEOUT") or 10)
        payloads = self.get_option("PAYLOADS").lower() == "true"
        delay    = float(self.get_option("DELAY") or 0.5)

        if not target.startswith(("http://", "https://")):
            target = "https://" + target

        client = CLVXHTTPClient(timeout=timeout, delay=delay)

        print_section(f"WAF/CDN Detection — {target}")
        findings = []

        print_status("Sending baseline request...", "run")
        code, body, headers = client.get(target, follow_redirects=False)

        if code == 0:
            print_status("Target unreachable.", "error")
            return []

        print_status(
            f"HTTP {code}  "
            f"Server: {Colors.WHITE}{headers.get('server', headers.get('Server', '?'))}{Colors.RESET}",
            "info"
        )

        print_status("Fingerprinting from response headers and body...", "run")
        detected = self._fingerprint(code, body, headers)

        if detected:
            for name, category in detected:
                color = Colors.RED if "WAF" in category else \
                        Colors.YELLOW if "CDN" in category else Colors.CYAN
                print(f"  {color}[{category}]{Colors.RESET} "
                      f"{Colors.BOLD}{Colors.WHITE}{name}{Colors.RESET} detected")
                findings.append(self._finding(
                    "INFO", f"Detected: {name}",
                    target, f"Category: {category}"
                ))
        else:
            print_status("No known WAF/CDN fingerprint detected.", "info")

        print()
        print_status("Response headers:", "info")
        security_headers = [
            "server", "x-powered-by", "cf-ray", "x-amz-cf-id",
            "x-cache", "via", "x-varnish", "x-sucuri-id",
            "strict-transport-security", "x-frame-options",
        ]
        for h in security_headers:
            val = headers.get(h, headers.get(h.title(), ""))
            if val:
                print(f"  {Colors.DARK_GRAY}{h:<35}{Colors.RESET}"
                      f"{Colors.WHITE}{val[:80]}{Colors.RESET}")

        if payloads:
            print()
            print_status("Probing WAF behaviour with attack payloads...", "run")
            findings += self._probe_waf(target, client)

        print()
        print_status(
            f"Detection complete. "
            f"Found: {Colors.WHITE}{', '.join(set(n for n, _ in detected)) or 'nothing identified'}{Colors.RESET}",
            "ok"
        )
        return findings

    def _fingerprint(self, code, body, headers) -> list:
        detected = set()
        lower_body    = body.lower()
        lower_headers = {k.lower(): v.lower() for k, v in headers.items()}
        all_cookies   = lower_headers.get("set-cookie", "")

        for name, category, match_type, patterns in FINGERPRINTS:
            for pattern in patterns:
                pattern = pattern.lower()
                matched = False
                if match_type == "header_key":
                    matched = pattern in lower_headers
                elif match_type == "header_val":
                    matched = any(pattern in v for v in lower_headers.values())
                elif match_type == "body":
                    matched = pattern in lower_body
                elif match_type == "cookie":
                    matched = pattern in all_cookies
                if matched:
                    detected.add((name, category))
                    break

        return list(detected)

    def _probe_waf(self, base_url: str, client: CLVXHTTPClient) -> list:
        findings = []
        base_code, _, _ = client.get(base_url)

        for label, suffix in WAF_TEST_PAYLOADS:
            if suffix is None:
                for ua in SCANNER_UAS:
                    code, body, hdrs = client.get(
                        base_url,
                        headers={"User-Agent": ua},
                        follow_redirects=False
                    )
                    if code in (403, 406, 429, 503) and code != base_code:
                        print(f"  {Colors.RED}[BLOCK]{Colors.RESET}  "
                              f"Scanner UA blocked: {Colors.YELLOW}{ua}{Colors.RESET} → HTTP {code}")
                        findings.append(self._finding(
                            "INFO", "WAF blocks scanner User-Agents",
                            base_url, f"UA: {ua} → HTTP {code}"
                        ))
                        break
                    else:
                        print(f"  {Colors.GREEN}[PASS]{Colors.RESET}   "
                              f"Scanner UA not blocked: {Colors.DARK_GRAY}{ua}{Colors.RESET} → {code}")
            else:
                url  = base_url + suffix
                code, body, hdrs = client.get(url, follow_redirects=False)
                if code in (403, 406, 429, 503):
                    print(f"  {Colors.RED}[BLOCK]{Colors.RESET}  "
                          f"{label} → HTTP {Colors.YELLOW}{code}{Colors.RESET} (WAF active)")
                    findings.append(self._finding(
                        "INFO", f"WAF blocks: {label}",
                        url, f"HTTP {code}"
                    ))
                elif code == base_code:
                    print(f"  {Colors.GREEN}[PASS]{Colors.RESET}   "
                          f"{label} → HTTP {code} (not blocked)")
                    findings.append(self._finding(
                        "MEDIUM", f"Payload not blocked: {label}",
                        url,
                        f"WAF did not block this payload (HTTP {code})"
                    ))
                else:
                    print(f"  {Colors.CYAN}[INFO]{Colors.RESET}   "
                          f"{label} → HTTP {code}")

        return findings
